(()=>{'use strict';
const slides=[...document.querySelectorAll('.slide')],wrap=document.querySelector('#stage-wrap'),stage=document.querySelector('#stage'),overview=document.querySelector('#overview'),frame=document.querySelector('#recording');
const targetSeconds=[33,66,77,62,38,56,60,68,70];let notesData=[],timings=null,index=0,notesOpen=false,timerOpen=false,running=false,elapsed=0,slideElapsed=0,lastTick=performance.now(),touchStart=null;
const slideTitle=s=>s.querySelector('h1,h2').innerHTML.replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim();
const $=s=>document.querySelector(s),format=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function fit(){if(innerWidth<=700){stage.style.transform='none';return;}const r=wrap.getBoundingClientRect();stage.style.transform=`scale(${Math.min((r.width-24)/1280,(r.height-14)/720)})`;}
function fitRecorder(){try{if(frame.getAttribute('src')&&frame.contentDocument?.body)frame.style.height=innerWidth<=700?frame.contentDocument.body.scrollHeight+'px':'';}catch{}}
function pauseRecording(){if(frame.contentWindow)frame.contentWindow.postMessage({type:'asena-recorder-pause'},location.origin);try{frame.contentDocument?.querySelectorAll('video,audio').forEach(v=>v.pause());}catch{}}
function syncNotes(){const n=notesData.find(n=>n.id===slides[index].dataset.id)||notesData[index];$('#notes-heading').textContent=`${index+1}. ${slideTitle(slides[index])}`;$('#notes-content').replaceChildren();if(!n){$('#notes-content').textContent='Presenter script is loading.';return;}const script=Array.isArray(n.script)?n.script.join('\n\n'):n.script||n.notes||'';for(const line of String(script).split(/\n\n+/)){const p=document.createElement('p');p.textContent=line;$('#notes-content').append(p);}if(n.stageDirection){const p=document.createElement('p');p.style.color='#b7c99f';p.textContent=`Stage: ${n.stageDirection}`;$('#notes-content').append(p);}}
function show(next,replace=false){next=Math.max(0,Math.min(slides.length-1,next));if(next!==index){pauseRecording();slideElapsed=0;}index=next;slides.forEach((s,i)=>{s.classList.toggle('active',i===index);s.setAttribute('aria-hidden',String(i!==index));});wrap.scrollTop=0;$('#slide-position').textContent=`${index+1} / ${slides.length}`;$('#progress-fill').style.width=`${100*(index+1)/slides.length}%`;$('#prev-button').disabled=index===0;$('#next-button').disabled=index===slides.length-1;document.title=`${index+1} · ${slideTitle(slides[index])} — ASENA`;const hash='#'+slides[index].dataset.id;if(location.hash!==hash)history[replace?'replaceState':'pushState'](null,'',hash);$('#overview-grid').querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-current',String(i===index)));if(slides[index].dataset.id==='records'&&!frame.getAttribute('src'))frame.src=frame.dataset.src;syncNotes();updateTimer();}
function panel(){const open=notesOpen||timerOpen;$('#presenter-panel').hidden=!open;$('#notes-panel').hidden=!notesOpen;$('#timer-panel').hidden=!timerOpen;$('#notes-button').setAttribute('aria-pressed',String(notesOpen));$('#timer-button').setAttribute('aria-pressed',String(timerOpen));if(notesOpen)syncNotes();}
function toggleNotes(){notesOpen=!notesOpen;panel();}function toggleTimer(){timerOpen=!timerOpen;panel();}function toggleOverview(){if(overview.open)overview.close();else{pauseRecording();overview.showModal();}}
function fullScreen(){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.();}
function updateTimer(){const target=timings?.totalSeconds||targetSeconds.reduce((a,b)=>a+b,0);$('#timer-elapsed').textContent=format(elapsed);$('#timer-target').textContent=`/ ${format(target)} target`;const per=timings?.slides?.find(s=>s.id===slides[index].dataset.id);$('#slide-timer').textContent=`This slide ${format(slideElapsed)} / ${format(per?.targetSeconds||per?.durationSeconds||targetSeconds[index])}`;$('#timer-start').textContent=running?'Pause':'Start';}
$('#prev-button').addEventListener('click',()=>show(index-1));$('#next-button').addEventListener('click',()=>show(index+1));$('#overview-button').addEventListener('click',toggleOverview);$('#overview-close').addEventListener('click',()=>overview.close());$('#notes-button').addEventListener('click',toggleNotes);$('#timer-button').addEventListener('click',toggleTimer);$('#fullscreen-button').addEventListener('click',fullScreen);$('#presenter-close').addEventListener('click',()=>{notesOpen=false;timerOpen=false;panel();});$('#timer-start').addEventListener('click',()=>{running=!running;lastTick=performance.now();updateTimer();});$('#timer-reset').addEventListener('click',()=>{running=false;elapsed=0;slideElapsed=0;updateTimer();});
slides.forEach((slide,i)=>{const button=document.createElement('button');button.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><strong></strong>`;button.querySelector('strong').textContent=slideTitle(slide);button.addEventListener('click',()=>{show(i);overview.close();});$('#overview-grid').append(button);});
addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.metaKey||e.ctrlKey||e.altKey)return;if(overview.open){if(e.key==='o'||e.key==='O')overview.close();return;}switch(e.key){case'ArrowRight':case'PageDown':case' ':e.preventDefault();show(index+1);break;case'ArrowLeft':case'PageUp':e.preventDefault();show(index-1);break;case'Home':e.preventDefault();show(0);break;case'End':e.preventDefault();show(slides.length-1);break;case'o':case'O':toggleOverview();break;case'n':case'N':toggleNotes();break;case't':case'T':toggleTimer();break;case'f':case'F':fullScreen();break;case'Escape':notesOpen=false;timerOpen=false;panel();break;}});
wrap.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStart={x:t.clientX,y:t.clientY};},{passive:true});wrap.addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;touchStart=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.6)show(index+(dx<0?1:-1));},{passive:true});
addEventListener('resize',()=>{fit();drawChart();fitRecorder();});addEventListener('hashchange',()=>{const next=slides.findIndex(s=>'#'+s.dataset.id===location.hash);if(next>=0)show(next,true);});addEventListener('pagehide',pauseRecording);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseRecording();});
setInterval(()=>{const now=performance.now();if(running){const dt=(now-lastTick)/1000;elapsed+=dt;slideElapsed+=dt;updateTimer();}lastTick=now;},200);
frame.addEventListener('load',()=>{try{const doc=frame.contentDocument;if(!doc)return;const css=doc.createElement('style');css.textContent='.recorder-head,.session,footer,.sample-details,.play-note{display:none!important}.recorder{border:0;border-radius:0}.camera-panel,.body-panel{padding:15px 17px}.panel-head{margin-bottom:9px}.panel-head h2{font-size:15px}.panel-head>span{font-size:10px}.camera-view{aspect-ratio:2.7/1}.robot-view{min-height:175px}.knee-chart{max-height:75px}.trace-title{margin-top:13px;font-size:11px}.state-strip{margin-top:9px;padding-top:9px}.state-strip span{font-size:9px}.state-strip b{font-size:16px}.transport{padding:12px 17px}.body-status{font-size:10px}@media(max-width:560px){.robot-view{height:235px;min-height:0}.body-panel,.camera-panel{padding:16px}.transport{padding:15px}.panel-head>span{font-size:10px}.state-strip span{font-size:10px}.state-strip b{font-size:16px}}';doc.head.append(css);fitRecorder();if(slides[index].dataset.id!=='records')pauseRecording();}catch{}});
let csvRows=[];function drawChart(){if(!csvRows.length)return;const mobile=innerWidth<=700,W=mobile?590:1152,H=mobile?420:365,L=mobile?54:68,R=mobile?52:94,T=25,B=mobile?52:45,x=p=>L+(p-1)*(W-L-R)/9,y=v=>T+(100-v)*(H-T-B)/60;const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);const add=(tag,attrs,txt)=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(txt!==undefined)e.textContent=txt;svg.append(e);return e;};for(let v=40;v<=100;v+=20){add('line',{x1:L,y1:y(v),x2:W-R,y2:y(v),stroke:'#d6ddd3','stroke-width':1});add('text',{x:L-14,y:y(v)+5,'text-anchor':'end',fill:'#627673','font-size':mobile?17:15},v);}for(let p=1;p<=10;p++){add('text',{x:x(p),y:H-B+26,'text-anchor':'middle',fill:'#627673','font-size':mobile?17:15},p);}add('text',{x:L,y:12,fill:'#627673','font-size':mobile?16:14},'Success (%)');add('text',{x:(L+W-R)/2,y:H-3,'text-anchor':'middle',fill:'#627673','font-size':mobile?17:14},'Pass');const names=['R2R + policy','R2R agent only','RxR + policy','RxR agent only'],colors=['#187e80','#187e80','#c07843','#c07843'];names.forEach((name,i)=>{const points=csvRows.map(r=>[x(+r.Pass),y(+r[name])]);add('polyline',{points:points.map(p=>p.join(',')).join(' '),fill:'none',stroke:colors[i],'stroke-width':i%2?2.8:4,'stroke-dasharray':i%2?'9 7':'none','stroke-linecap':'round','stroke-linejoin':'round'});points.forEach(p=>add('circle',{cx:p[0],cy:p[1],r:i%2?3:4,fill:i%2?'#f6f5ee':colors[i],stroke:colors[i],'stroke-width':1.5}));const end=csvRows.at(-1)[name],offset=i===0?-9:i===1?15:4;add('text',{x:x(10)+12,y:y(+end)+offset,fill:colors[i],'font-size':mobile?19:21,'font-weight':600},end+'%');});$('#rsi-chart').replaceChildren(svg);}
fetch('navigation-evolution.csv').then(r=>r.text()).then(text=>{const lines=text.trim().split(/\r?\n/),keys=lines.shift().split(',');csvRows=lines.map(line=>Object.fromEntries(line.split(',').map((v,i)=>[keys[i],v])));drawChart();});
fetch('script.json').then(r=>r.json()).then(data=>{notesData=Array.isArray(data)?data:data.slides||[];syncNotes();});fetch('timing.json').then(r=>r.ok?r.json():null).then(data=>{timings=data;updateTimer();}).catch(()=>{});
fit();const initial=slides.findIndex(s=>'#'+s.dataset.id===location.hash);show(initial<0?0:initial,true);if(new URLSearchParams(location.search).has('rehearse')){notesOpen=true;timerOpen=true;panel();}
})();
