(()=>{'use strict';
const slides=[...document.querySelectorAll('.slide')],wrap=document.querySelector('#stage-wrap'),stage=document.querySelector('#stage'),overview=document.querySelector('#overview'),frame=document.querySelector('#recording');
const previewMode=new URLSearchParams(location.search).has('presenterPreview');
const $=selector=>document.querySelector(selector),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const targetSeconds=[33,66,77,62,38,56,60,68,70];
const builds={asena:[[]],composition:[['.composition-top'],['.tool-fork','.composition-demo'],['.execution-band','.feedback-line','.source']],workspace:[['.canonical'],['.seed-line','.workers-row'],['.gather-line','.consolidation','.workspace-loop','.takeaway']],safety:[['.code-boundary'],['.motion-boundary','.gesture-demo-link','.source']],training:[['.existing-loop'],['.shared-layer','.proposed-loop','.takeaway']],policy:[['.policy-top'],['.policy-results','.takeaway','.source']],efficiency:[['.efficiency-key','.efficiency-row:first-child'],['.efficiency-row:last-child','.takeaway','.source']],rsi:[[],[],['.rsi-context','.source']],records:[['.recording-wrap'],['.recording-copy','.records-ending','.source']]};
let notesData=[],timings=null,index=0,step=0,notesOpen=false,timerOpen=false,running=false,elapsed=0,slideElapsed=0,lastTick=performance.now(),touchStart=null,csvRows=[],chartPass=1,chartTimer=0,entryToken=0;
const format=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const slideTitle=s=>s.querySelector('h1,h2').innerHTML.replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,'').replace(/\s+/g,' ').trim();
const count=i=>(builds[slides[i].dataset.id]||[[]]).length;
const stepIndicator=document.createElement('div');stepIndicator.id='build-indicator';stepIndicator.className='build-indicator';stepIndicator.setAttribute('aria-live','polite');$('#slide-position').after(stepIndicator);
slides.forEach(slide=>{const groups=builds[slide.dataset.id]||[[]];groups.forEach((selectors,n)=>selectors.forEach(selector=>slide.querySelectorAll(selector).forEach(element=>{element.dataset.build=n;element.classList.add('build-part');})));slide.querySelectorAll('.worker').forEach((worker,n)=>worker.style.setProperty('--worker-delay',`${n*140}ms`));slide.querySelectorAll('video').forEach(video=>{video.removeAttribute('autoplay');video.muted=true;video.playsInline=true;video.pause();});});
function fit(){if(previewMode){stage.style.transform=`scale(${Math.min(innerWidth/1280,innerHeight/720)})`;return;}if(innerWidth<=700){stage.style.transform='none';return;}const r=wrap.getBoundingClientRect();stage.style.transform=`scale(${Math.min((r.width-24)/1280,(r.height-14)/720)})`;}
function fitRecorder(){try{if(frame?.getAttribute('src')&&frame.contentDocument?.body)frame.style.height=innerWidth<=700?frame.contentDocument.body.scrollHeight+'px':'';}catch{}}
function pauseRecording(){if(frame?.contentWindow)frame.contentWindow.postMessage({type:'asena-recorder-pause'},location.origin);try{frame?.contentDocument?.querySelectorAll('video,audio').forEach(v=>v.pause());}catch{}}
function pauseAllMedia(){document.querySelectorAll('.slide video,.slide audio').forEach(video=>video.pause());pauseRecording();}
function showVideoFallback(video){if(video.parentElement.querySelector('.media-play-fallback'))return;const button=document.createElement('button');button.className='media-play-fallback';button.textContent='▶ Play video';button.addEventListener('click',event=>{event.stopPropagation();if(!video.paused){video.pause();button.textContent='▶ Play video';}else playVideo(video,true);});video.parentElement.append(button);}
function playVideo(video,manual=false){if(previewMode||document.hidden||document.querySelector('dialog[open]')||!video.closest('.slide.active')||video.closest('.build-hidden'))return;if(!manual&&reduced.matches){showVideoFallback(video);return;}video.muted=true;video.playsInline=true;if(video.dataset.src&&!video.getAttribute('src'))video.src=video.dataset.src;const promise=video.play();if(promise)promise.then(()=>{const button=video.parentElement.querySelector('.media-play-fallback');if(reduced.matches&&button)button.textContent='Ⅱ Pause video';else button?.remove();}).catch(()=>{showVideoFallback(video);});}
function activeVideos(){slides[index].querySelectorAll('video').forEach(video=>{if(video.closest('.build-hidden')){video.pause();delete video.dataset.startedEntry;return;}if(video.dataset.startedEntry!==String(entryToken)){video.dataset.startedEntry=String(entryToken);playVideo(video);}});}
function startRecorder(){if(previewMode||!frame||document.hidden||document.querySelector('dialog[open]')||reduced.matches||slides[index].dataset.id!=='records')return;try{const doc=frame.contentDocument,button=doc?.querySelector('#play'),video=doc?.querySelector('#camera');if(!button||button.disabled||!video)return;if(doc.querySelector('#play-label')?.textContent!=='Pause')button.click();}catch{}}
function syncNotes(){const n=notesData.find(n=>n.id===slides[index].dataset.id)||notesData[index];$('#notes-heading').textContent=`${index+1}. ${slideTitle(slides[index])}`;$('#notes-content').replaceChildren();if(!n){$('#notes-content').textContent='Presenter script is loading.';return;}const script=Array.isArray(n.script)?n.script.join('\n\n'):n.script||n.notes||'';for(const line of String(script).split(/\n\n+/)){const p=document.createElement('p');p.textContent=line;$('#notes-content').append(p);}if(n.stageDirection){const p=document.createElement('p');p.style.color='#b7c99f';p.textContent=`Stage: ${n.stageDirection}`;$('#notes-content').append(p);}}
function updateNavigation(){const total=count(index);$('#prev-button').disabled=index===0&&step===0;$('#next-button').disabled=index===slides.length-1&&step===total-1;$('#next-button').title=step<total-1?'Reveal next step (→ / Space)':'Next slide (→ / Space)';$('#prev-button').title=step>0?'Previous step (←)':'Previous slide (←)';stepIndicator.innerHTML=`<span>Step ${step+1}/${total}</span><span class="build-dots" aria-hidden="true">${Array.from({length:total},(_,n)=>`<i class="${n<=step?'shown':''}"></i>`).join('')}</span>`;stepIndicator.dataset.total=total;}
function applyBuild(next,{animate=true,updateHash=true}={}){const slide=slides[index],previous=step;step=Math.max(0,Math.min(count(index)-1,next));slide.dataset.step=step;slide.querySelectorAll('.build-part').forEach(element=>{const visible=Number(element.dataset.build)<=step,wasHidden=element.classList.contains('build-hidden');element.classList.toggle('build-hidden',!visible);element.classList.toggle('build-visible',visible);element.classList.toggle('build-current',Number(element.dataset.build)===step);element.setAttribute('aria-hidden',String(!visible));element.inert=!visible;if(visible&&wasHidden&&animate&&!reduced.matches){element.classList.remove('build-enter');void element.offsetWidth;element.classList.add('build-enter');}else element.classList.remove('build-enter');});updateNavigation();if(updateHash){const hash='#'+slide.dataset.id+(step?'/'+(step+1):'');history.replaceState(null,'',hash);}if(slide.dataset.id==='rsi')revealPasses([1,5,10][step],animate);activeVideos();if(innerWidth<=700&&animate){if(step<previous)wrap.scrollTop=0;else{const current=slide.querySelector('.build-current');if(current&&current.getBoundingClientRect().top>wrap.getBoundingClientRect().bottom-100)current.scrollIntoView({block:'center',behavior:reduced.matches?'instant':'smooth'});}}dispatchEvent(new CustomEvent('asena-buildchange',{detail:{index,id:slide.dataset.id,step}}));}
function show(next,replace=false,targetStep=0){next=Math.max(0,Math.min(slides.length-1,next));pauseAllMedia();clearInterval(chartTimer);if(next!==index)slideElapsed=0;index=next;entryToken++;step=0;slides.forEach((slide,i)=>{slide.classList.toggle('active',i===index);slide.setAttribute('aria-hidden',String(i!==index));slide.inert=i!==index;});wrap.scrollTop=0;$('#slide-position').textContent=`${index+1} / ${slides.length}`;$('#progress-fill').style.width=`${100*(index+1)/slides.length}%`;document.title=`${index+1} · ${slideTitle(slides[index])} — ASENA`;const hash='#'+slides[index].dataset.id+(targetStep?'/'+(targetStep+1):'');if(location.hash!==hash)history[replace?'replaceState':'pushState'](null,'',hash);$('#overview-grid').querySelectorAll('button').forEach((button,i)=>button.setAttribute('aria-current',String(i===index)));applyBuild(targetStep,{animate:false,updateHash:false});if(!previewMode&&slides[index].dataset.id==='records'&&frame){if(!frame.getAttribute('src'))frame.src=frame.dataset.src;else startRecorder();}syncNotes();updateTimer();dispatchEvent(new CustomEvent('asena-slidechange',{detail:{index,id:slides[index].dataset.id,step}}));}
function forward(){if(step<count(index)-1)applyBuild(step+1);else if(index<slides.length-1)show(index+1);}
function back(){if(step>0)applyBuild(step-1);else if(index>0)show(index-1,false,count(index-1)-1);}
function panel(){const open=notesOpen||timerOpen;$('#presenter-panel').hidden=!open;$('#notes-panel').hidden=!notesOpen;$('#timer-panel').hidden=!timerOpen;$('#notes-button').setAttribute('aria-pressed',String(notesOpen));$('#timer-button').setAttribute('aria-pressed',String(timerOpen));if(notesOpen)syncNotes();}
function toggleNotes(){if(window.TALK_PRESENTER){window.TALK_PRESENTER.open();return;}notesOpen=!notesOpen;panel();}function toggleTimer(){if(window.TALK_PRESENTER){window.TALK_PRESENTER.open();return;}timerOpen=!timerOpen;panel();}
function toggleOverview(){if(overview.open)overview.close();else{pauseAllMedia();overview.showModal();}}
function fullScreen(){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.();}
function updateTimer(){const target=timings?.totalSeconds||targetSeconds.reduce((a,b)=>a+b,0);$('#timer-elapsed').textContent=format(elapsed);$('#timer-target').textContent=`/ ${format(target)} target`;const per=timings?.slides?.find(s=>s.id===slides[index].dataset.id);$('#slide-timer').textContent=`This slide ${format(slideElapsed)} / ${format(per?.targetSeconds||per?.durationSeconds||targetSeconds[index])}`;$('#timer-start').textContent=running?'Pause':'Start';}
$('#prev-button').addEventListener('click',back);$('#next-button').addEventListener('click',forward);$('#overview-button').addEventListener('click',toggleOverview);$('#overview-close').addEventListener('click',()=>overview.close());$('#notes-button').addEventListener('click',toggleNotes);$('#timer-button').addEventListener('click',toggleTimer);$('#fullscreen-button').addEventListener('click',fullScreen);$('#presenter-close').addEventListener('click',()=>{notesOpen=false;timerOpen=false;panel();});$('#timer-start').addEventListener('click',()=>{running=!running;lastTick=performance.now();updateTimer();});$('#timer-reset').addEventListener('click',()=>{running=false;elapsed=0;slideElapsed=0;updateTimer();});
slides.forEach((slide,i)=>{const button=document.createElement('button');button.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><strong></strong>`;button.querySelector('strong').textContent=slideTitle(slide);button.addEventListener('click',()=>{overview.close();show(i);});$('#overview-grid').append(button);});
overview.addEventListener('close',()=>{entryToken++;activeVideos();if(slides[index].dataset.id==='records')startRecorder();});
$('#overview>p').textContent='← → / Space Build and navigate · O Overview · N Presenter · F Full screen';
addEventListener('keydown',event=>{if(/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||event.metaKey||event.ctrlKey||event.altKey)return;if(document.querySelector('dialog[open]:not(#overview)'))return;if(overview.open){if(event.key.toLowerCase()==='o')overview.close();return;}if(event.key===' '&&event.target.closest('button,a,video'))return;switch(event.key){case'ArrowRight':case'PageDown':case' ':event.preventDefault();forward();break;case'ArrowLeft':case'PageUp':event.preventDefault();back();break;case'Home':event.preventDefault();show(0);break;case'End':event.preventDefault();show(slides.length-1);break;case'o':case'O':toggleOverview();break;case'n':case'N':toggleNotes();break;case't':case'T':toggleTimer();break;case'f':case'F':fullScreen();break;case'Escape':notesOpen=false;timerOpen=false;panel();break;}});
wrap.addEventListener('touchstart',event=>{if(event.target.closest('video,button,input,a'))return;const touch=event.changedTouches[0];touchStart={x:touch.clientX,y:touch.clientY};},{passive:true});wrap.addEventListener('touchend',event=>{if(!touchStart)return;const touch=event.changedTouches[0],dx=touch.clientX-touchStart.x,dy=touch.clientY-touchStart.y;touchStart=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.6){if(dx<0)forward();else back();}},{passive:true});
function fromHash(){const [id,build]=location.hash.slice(1).split('/'),next=slides.findIndex(slide=>slide.dataset.id===id);show(next<0?0:next,true,Math.max(0,(Number(build)||1)-1));}
addEventListener('resize',()=>{fit();drawChart();fitRecorder();});addEventListener('hashchange',fromHash);addEventListener('pagehide',pauseAllMedia);document.addEventListener('visibilitychange',()=>{document.documentElement.classList.toggle('deck-suspended',document.hidden);if(document.hidden)pauseAllMedia();else{entryToken++;activeVideos();if(slides[index].dataset.id==='records')startRecorder();}});reduced.addEventListener('change',()=>{if(reduced.matches){pauseAllMedia();slides[index].querySelectorAll('video').forEach(showVideoFallback);}drawChart();});
setInterval(()=>{const now=performance.now();if(running){const dt=(now-lastTick)/1000;elapsed+=dt;slideElapsed+=dt;updateTimer();}lastTick=now;},200);
frame?.addEventListener('load',()=>{try{const doc=frame.contentDocument;if(!doc)return;const css=doc.createElement('style');css.textContent='.recorder-head,.session,footer,.sample-details,.play-note{display:none!important}.recorder{border:0;border-radius:0}.camera-panel,.body-panel{padding:15px 17px}.panel-head{margin-bottom:9px}.panel-head h2{font-size:15px}.panel-head>span{font-size:10px}.camera-view{aspect-ratio:2.7/1}.robot-view{min-height:175px}.knee-chart{max-height:75px}.trace-title{margin-top:13px;font-size:11px}.state-strip{margin-top:9px;padding-top:9px}.state-strip span{font-size:9px}.state-strip b{font-size:16px}.transport{padding:12px 17px}.body-status{font-size:10px}@media(max-width:560px){.robot-view{height:235px;min-height:0}.body-panel,.camera-panel{padding:16px}.transport{padding:15px}.panel-head>span{font-size:10px}.state-strip span{font-size:10px}.state-strip b{font-size:16px}}';doc.head.append(css);fitRecorder();if(slides[index].dataset.id==='records')startRecorder();else pauseRecording();}catch{}});
function revealPasses(target,animate){clearInterval(chartTimer);if(!animate||reduced.matches||target<=chartPass){chartPass=target;drawChart();return;}chartTimer=setInterval(()=>{chartPass++;drawChart();if(chartPass>=target)clearInterval(chartTimer);},190);}
function drawChart(){if(!csvRows.length)return;const mobile=innerWidth<=700,W=mobile?590:1152,H=mobile?420:365,L=mobile?54:68,R=mobile?52:94,T=25,B=mobile?52:45,x=pass=>L+(pass-1)*(W-L-R)/9,y=value=>T+(100-value)*(H-T-B)/60;const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.dataset.pass=chartPass;const add=(tag,attributes,text)=>{const element=document.createElementNS(NS,tag);Object.entries(attributes).forEach(([key,value])=>element.setAttribute(key,value));if(text!==undefined)element.textContent=text;svg.append(element);return element;};for(let value=40;value<=100;value+=20){add('line',{x1:L,y1:y(value),x2:W-R,y2:y(value),stroke:'#d6ddd3','stroke-width':1});add('text',{x:L-14,y:y(value)+5,'text-anchor':'end',fill:'#627673','font-size':mobile?17:15},value);}for(let pass=1;pass<=10;pass++)add('text',{x:x(pass),y:H-B+26,'text-anchor':'middle',fill:pass<=chartPass?'#627673':'#aebbb2','font-size':mobile?17:15},pass);add('text',{x:L,y:12,fill:'#627673','font-size':mobile?16:14},'Success (%)');add('text',{x:(L+W-R)/2,y:H-3,'text-anchor':'middle',fill:'#627673','font-size':mobile?17:14},`Pass ${chartPass} / 10`);const names=['R2R + policy','R2R agent only','RxR + policy','RxR agent only'],colors=['#187e80','#187e80','#c07843','#c07843'];names.forEach((name,i)=>{const points=csvRows.slice(0,chartPass).map(row=>[x(+row.Pass),y(+row[name])]);add('polyline',{points:points.map(point=>point.join(',')).join(' '),fill:'none',stroke:colors[i],'stroke-width':i%2?2.8:4,'stroke-dasharray':i%2?'9 7':'none','stroke-linecap':'round','stroke-linejoin':'round'});points.forEach(point=>add('circle',{cx:point[0],cy:point[1],r:i%2?3:4,fill:i%2?'#f6f5ee':colors[i],stroke:colors[i],'stroke-width':1.5}));const end=csvRows[chartPass-1][name],values=names.map(n=>+csvRows[chartPass-1][n]);let offset=4;if(Math.abs(values[0]-values[1])<4&&i<2)offset=i===0?-9:17;if(Math.abs(values[2]-values[3])<4&&i>=2)offset=i===2?-9:17;add('text',{x:x(chartPass)+12,y:y(+end)+offset,fill:colors[i],'font-size':mobile?19:21,'font-weight':600},end+'%');});$('#rsi-chart').replaceChildren(svg);$('#rsi-chart').setAttribute('aria-label',`Measured success through pass ${chartPass} of 10. `+names.map(name=>`${name}: ${csvRows[chartPass-1][name]} percent`).join('. '));}
fetch('navigation-evolution.csv').then(response=>response.text()).then(text=>{const lines=text.trim().split(/\r?\n/),keys=lines.shift().split(',');csvRows=lines.map(line=>Object.fromEntries(line.split(',').map((value,i)=>[keys[i],value])));drawChart();});
fetch('script.json').then(response=>response.json()).then(data=>{notesData=Array.isArray(data)?data:data.slides||[];syncNotes();});fetch('timing.json').then(response=>response.ok?response.json():null).then(data=>{timings=data;updateTimer();}).catch(()=>{});
addEventListener('beforeprint',()=>{pauseAllMedia();chartPass=10;drawChart();});addEventListener('afterprint',()=>applyBuild(step,{animate:false}));
window.TALK_DECK={key:'asena-talk',name:'ASENA',state:()=>({index,step,maxStep:count(index)-1,slideCount:slides.length,title:slideTitle(slides[index])}),slides:()=>slides.map((slide,i)=>({title:slideTitle(slide),maxStep:count(i)-1,seconds:targetSeconds[i]})),show:(i,s=0)=>show(i,true,s),next:forward,previous:back,hideNotes:()=>{notesOpen=false;timerOpen=false;panel();},pause:pauseAllMedia};
fit();fromHash();if(!previewMode&&new URLSearchParams(location.search).has('rehearse')){notesOpen=true;timerOpen=true;panel();}
})();
