# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sifei Liu
name: Sifei Liu
position: Sr. Research Scientist 
email: zwrq0star@gmail.com
description: >-
  I am a stuff-level senior research scientist at [NVIDIA](https://www.nvidia.com/en-us/research/), the [LPR](https://research.nvidia.com/labs/lpr/) team led by [Jan Kautz](https://jankautz.com/), where I work on generalizable representation learning for images, videos and 3D. Previously, I was a Ph. D student at the [VLLAB](http://vllab.ucmerced.edu/) advised by [Ming-Hsuan Yang](http://faculty.ucmerced.edu/mhyang/).

  I was the recipient of the Baidu Graduate Fellowship in 2013, the NVIDIA Pioneering Research Award in 2017, Rising Star EECS in 2019, and nominated for VentureBeat Women in AI Award in 2020.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sifeiliu.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SifeiL
github_username: Liusifei
google_scholar: j4pcHV4AAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
