# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sifei Liu
name: Sifei Liu
position: Sr. Research Scientist 
email: zwrq0star@gmail.com
description: >-
  I currently hold the position of a staff-level Senior Research Scientist at [NVIDIA](https://www.nvidia.com/en-us/research/), where I am part of the [LPR](https://research.nvidia.com/labs/lpr/) team led by [Jan Kautz](https://jankautz.com/). My work primarily revolves around the development of generalizable visual representation learning for images, videos, and 3D content. Prior to this, I pursued my Ph.D. at the [VLLAB](http://vllab.ucmerced.edu/), under the guidance of [Ming-Hsuan Yang](http://faculty.ucmerced.edu/mhyang/).

  Over the years, I've been fortunate to receive several prestigious awards and recognitions. In 2013, I was honored with the Baidu Graduate Fellowship. This was followed by the NVIDIA Pioneering Research Award in 2017, and the Rising Star EECS accolade in 2019. Additionally, I was nominated for the VentureBeat Women in AI Award in 2020.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sifeiliu.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SifeiL
github_username: Liusifei
google_scholar: j4pcHV4AAAAJ
nv_site: https://research.nvidia.com/person/sifei-liu

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
